export const htmlContent:string = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <title>Generated HTML</title>
</head>
<body>
  <h1>Welcome to My CLI App</h1>
  <p>This HTML file was generated by a Node.js CLI tool!</p>
  <script src="js/script.js"></script>
</body>
</html>`;

export const readmecontent:string =`# Create-basic-app

This project was created using the **create-basic-app** CLI tool. It contains a basic folder structure for a web project.


## File Descriptions

- **index.html**: The main HTML file for your web project.
- **style.css**: Stylesheet for the project.
- **script.js**: JavaScript file for interactivity.

## How to Use

1. Open index.html in your preferred code editor or browser to start working on your project.
2. Add your custom CSS in 'style.css'.
3. Write JavaScript functions in 'script.js' to make your project interactive.

## Notes

- You can rename the files as needed.
- Feel free to add additional files or folders to extend the project.

## Happy Coding! ✨`;
export const gitignorecontent:string =`node_modules
.env`;
export const csscontent:string=`*{
    width:100%;
    height:1005;
    margin:0;
    padding:0;
    }`;

export const jscontent:string =`console.log("Hello world");`;